name=enchantiAudio-interface
version=0.1
author=Albert-Ngabo Niyonsenga
maintainer=Albert-Ngabo Niyonsenga
sentence=C++ Class for Audio Interfaces in Enchanti boards
paragraph=Tools for streaming and sending Audio accross multiple protocols
category=Signal Input/Output
url=https://github.com/aburt2/EnchantiAudio-Interface
architectures=*
